name       : autokey-py3
version    : 0.93.10
release    : 3
source     :
    - https://github.com/autokey-py3/autokey/archive/v0.93.10.tar.gz : ad2c7de897414095c2b3a1937d1d3196165809ef4067efc149f25894ab95d4b4
license    : GPL-3.0
component  : system.utils
summary    : Python 3 port of AutoKey, a desktop automation utility for Linux and X11 with new features
description: |
    AutoKey is a desktop automation utility for Linux and X11. It allows the automation of virtually
    any task by responding to typed abbreviations and hotkeys. It offers a full-featured GUI that
    makes it highly accessible for novices, as well as a scripting interface offering the
    full flexibility and power of the Python language.
builddeps  :
    - pkgconfig(python-3.5)
    - python3-dbus
rundeps    :
    - libappindicator
    - python-inotify
    - python3-dbus
    - python3-gobject
    - python-xlib
setup      : |
    %apply_patches
build      : |
    %python3_setup
install    : |
    %python3_install

    # remove Qt stuffs
    rm -rfv $installdir/usr/lib/python3.5/site-packages/autokey/qtui/
    rm -rfv $installdir/usr/share/kde4/
    rm -fv $installdir/usr/share/applications/autokey-qt.desktop
    rm -fv $installdir/usr/share/man/man1/autokey-qt.1
    rm -fv $installdir/usr/bin/autokey-qt
    rm -fv $installdir/usr/lib/python3.5/site-packages/autokey/__pycache__/qtapp.cpython-35.pyc
    rm -fv $installdir/usr/lib/python3.5/site-packages/autokey/qtapp.py

    rm -rfv $installdir/usr/share/icons/Humanity/
    rm -rfv $installdir/usr/share/icons/ubuntu-mono*/
