name       : autokey-py3
version    : 0.95.4
release    : 5
source     :
    - https://github.com/autokey/autokey/archive/v0.95.4.tar.gz : 7d132180a92d37c87598e2bd324a60175de6a5185eac0be3d513730104b7d00d
license    : GPL-3.0-or-later
component  :
    - system.utils
    - qt   : system.utils
summary    :
    - Python 3 port of AutoKey, a desktop automation utility for Linux and X11 with new features
    - qt   : AutoKey Qt front end
description: |
    AutoKey is a desktop automation utility for Linux and X11. It allows the automation of virtually any task by responding to typed abbreviations and hotkeys. It offers a full-featured GUI that makes it highly accessible for novices, as well as a scripting interface offering the full flexibility and power of the Python language.
patterns   :
    - qt   :
        - /usr/bin/autokey-qt
        - /usr/lib/python3.6/site-packages/autokey/__pycache__/qtapp.cpython-36.pyc
        - /usr/lib/python3.6/site-packages/autokey/qt*
        - /usr/share/applications/autokey-qt.desktop
        - /usr/share/man/man1/autokey-qt.1
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(dbus-python)
rundeps    :
    - libappindicator
    - python-inotify
    - python3-dbus
    - python3-gobject
    - python-xlib
    - qt   :
        - autokey-py3
        - python-qscintilla
setup      : |
    %patch -p1 < $pkgfiles/0001-remove-requires-dbus-python.patch
build      : |
    %python3_setup
install    : |
    %python3_install
