name       : autokey-py3
version    : 0.95.9
release    : 9
source     :
    - https://github.com/autokey/autokey/archive/v0.95.9.tar.gz : 46d42189d7a033ce9710395d2ddca685e83bd8792d6b25309e2446c4184063b5
license    : GPL-3.0-or-later
component  :
    - system.utils
    - qt : system.utils
summary    :
    - Python 3 port of AutoKey, a desktop automation utility for Linux and X11 with new features
    - qt : AutoKey Qt front end
description: |
    AutoKey is a desktop automation utility for Linux and X11. It allows the automation of virtually any task by responding to typed abbreviations and hotkeys. It offers a full-featured GUI that makes it highly accessible for novices, as well as a scripting interface offering the full flexibility and power of the Python language.
patterns   :
    - qt :
        - /usr/bin/autokey-qt
        - /usr/lib/python3.7/site-packages/autokey/__pycache__/qtapp.cpython-37.pyc
        - /usr/lib/python3.7/site-packages/autokey/qt*
        - /usr/share/applications/autokey-qt.desktop
        - /usr/share/man/man1/autokey-qt.1
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(dbus-python)
rundeps    :
    - libappindicator
    - python3-dbus
    - python-gobject
    - python-inotify
    - python-xlib
    - qt :
        - autokey-py3
        - python-qscintilla
build      : |
    %python3_setup
install    : |
    %python3_install
